<a href="https://colab.research.google.com/github/shafqat202/python-practice-/blob/main/Numpy%20beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 NumPy Basics: Creating & Randomizing

### Core Concepts:
*   **`np.arange(start, stop, step)`**: Works like the Python `range()` but creates a NumPy array.
*   **`np.linspace(start, stop, count)`**: Generates exactly `count` numbers evenly spaced between the start and stop.
*   **Randomness**: `np.random` generates numbers. Remember that `randint` produces whole numbers, while `random` produces decimals (floats).

In [43]:
import numpy as np

# Creating arrays with specific patterns
arrange=np.arange(1,11,3) # Start at 1, go up to 10, jump by 3
scale=np.linspace(1,10,3) # Give me 3 numbers perfectly spaced between 1 and 10
fourdmatrix=np.arange(24).reshape(2,2,2,3) # 24 numbers packed into a 4D structure

# Random number generation
a=np.random.random(12) # 12 random decimals between 0 and 1
print(a)
print()

b=np.random.randint(12) # A single random whole number up to 12
print(b)
print()

c=np.random.randint(1,100,5) # 5 random whole numbers between 1 and 100
print(c)
print()

d=np.random.randint(1,100,size=(5,3)) # A 5x3 grid of random numbers
print(d)

# Note: To reshape random ints, you MUST provide the size inside randint()
#t=np.random.randint(1,100, size=(3,3))
#print(t)

[0.92954322 0.70568871 0.1801622  0.93134997 0.70264149 0.06360834
 0.76096542 0.01668746 0.2053784  0.51410101 0.42615972 0.63080231]

4

[91 48 13 59 18]

[[47 27 46]
 [79 98 96]
 [81 11  1]
 [68 31  4]
 [92 21 94]]


AttributeError: 'int' object has no attribute 'reshape'

# 🏗️ Structural Changes & Shapes

### Core Concepts:
*   **`.reshape(rows, cols)`**: Changes the view of the data without changing the data itself. The total size (rows * cols) must match the number of elements.
*   **`np.zeros` & `np.ones`**: Quick way to initialize empty grids for math operations.
*   **`np.identity`**: Creates a square matrix with 1s on the diagonal—very important in linear algebra!

In [24]:
x=np.array([1,2,3,4,5,6,7,8])
# Turning a flat list into a 3D block (2x2x2)
matrix=x.reshape(2,2,2)
print(matrix)

# Quick ways to make grids filled with specific numbers
print(np.zeros((3,10),dtype=int)) # A 3x10 grid of zeros
print()

print(np.ones((3,10),dtype=int)*3) # Start with ones, then multiply everything by 3

# Identity matrix: 1s down the diagonal, 0s everywhere else
print(np.identity(4))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

[[3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 🔍 Metadata & Seeds

### Core Concepts:
*   **`np.random.seed()`**: This 'locks' the random numbers so your results are reproducible.
*   **Attributes**:
    *   `.ndim`: How many levels of brackets (dimensions) are there?
    *   `.shape`: What is the actual grid layout?
    *   `.size`: How many total items are inside?

In [44]:
import numpy as np
# Setting a 'seed' ensures the 'random' numbers are the same every time we run this
np.random.seed(84)

x=np.random.randint(500,600,size=(3,3))
print(x)

# Checking the 'metadata' of our array
print(x.ndim)  # Number of dimensions (e.g., 2D)
print(x.size)  # Total number of elements inside
print(x.shape) # The exact grid size (rows, columns)

# Use .reshape() to change the look of an existing sequence
print(np.arange(10).reshape(2,5))

[[542 589 556]
 [578 564 597]
 [574 568 533]]
2
9
(3, 3)
[[0 1 2 3 4]
 [5 6 7 8 9]]


# ⚡ Vectorization (NumPy Math)

### Core Concepts:
*   **Broadcasting**: In NumPy, you don't need loops. If you do `array + 10`, it automatically adds 10 to every single element inside. This makes NumPy incredibly fast for data science.

In [57]:
# Task 1: Basic range (start, stop, step)
a=np.arange(5,26,5)
print(a)

# Task 2: Getting specific points between two numbers
print(np.linspace(2,20,7)) # (start, stop, how_many_numbers)

# Task 3: Making a grid from a sequence
c=np.arange(12).reshape(3,4)

# Task 4 & 5: Zeros and Ones
print(np.zeros((2,5), dtype=int))
print(np.ones((3,3),dtype=int))

# Task 6: Identity matrix
print(np.identity(4))

# Task 7: Linear spacing practice
print(np.linspace(10,50,5))

# Task 8: Checking array attributes
print(c)
print(f"Shape: {c.shape}")

# Task 9: Math operations (NumPy does this to EVERY number in the array at once!)
print(c + 10)
print(c * 2)
print(c ** 2)

[ 5 10 15 20 25]
[ 2.  11.5 21. ]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[10. 20. 30. 40. 50.]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
